<?php
namespace Library\Core;
use app\Entities\User;
use Library\Core\Database\Pdo;

/**
 * Test component
 *
 * @author Nicolas Bonnici <nicolasbonnici@gmail.com>
 */
class Test extends \PHPUnit_Framework_TestCase
{

    const ACCESSORS_GETTER = 'getter';
    const ACCESSORS_SETTER = 'setter';

    public function __construct()
    {
        $_SERVER['SERVER_NAME'] = 'nbonnici.dev';
        $_SERVER['REQUEST_URI'] = '/';
        if (isset($_SESSION) === false || is_array($_SESSION) === false) {
            global $_SESSION;
            $_SESSION = array();
        }
        if (defined('TEST') === false) {
            define('TEST', true);
        }


        // Register autoload and load config for given staging environment
        include_once __DIR__ . '/Bootstrap.php';
        \Library\Core\Bootstrap::getInstance();
    }

    /**
     * Display class name before run all testcase methods
     */
    public static function setUpBeforeClass()
    {
        echo "\n" . get_called_class() . "\n";
    }
    
    /**
     * Switch method accessibility
     * 
     * @param string $sClassName
     * @param string $sMethodName
     * @return \ReflectionMethod
     */
    protected function setMethodAccessible($sClassName, $sMethodName)
    {
        $oReflectionClass = new \ReflectionClass($sClassName);
        $oMethod = $oReflectionClass->getMethod($sMethodName);
        $oMethod->setAccessible(true);
        return $oMethod;
    }

    /**
     * Retrieve class accessors
     *
     * @param mixed string|object $mClass
     * @return array
     */
    protected function getAccessors($mClass)
    {
        $oReflectedEmailNotification = new \ReflectionClass($mClass);

        $aAccessors = array();
        $aAccessors[self::ACCESSORS_GETTER] = array();
        $aAccessors[self::ACCESSORS_SETTER] = array();
        $aMethods = $oReflectedEmailNotification->getMethods();
        foreach ($aMethods as $iIndex => $oMethod) {
            if (substr($oMethod->name, 0, strlen('get')) === 'get') {
                $aAccessors[self::ACCESSORS_GETTER][] = $oMethod->name;
            }

            if (substr($oMethod->name, 0, strlen('set')) === 'set') {
                $aAccessors[self::ACCESSORS_SETTER][] = $oMethod->name;
            }
        }
        return $aAccessors;
    }

    protected static function cleanCreatedUsers($sUserEmailPattern)
    {
        // Clean created user from the register method unit test
        $oUser = new User();
        $oUser->loadByParameters(array(
            'mail' => $sUserEmailPattern
        ));

        if ($oUser->isLoaded() === true) {

            $oStatement = Pdo::dbQuery('
            SET FOREIGN_KEY_CHECKS=0;
            DELETE FROM `feedItem` WHERE `feed_idfeed` IN (SELECT `idfeed` FROM `feed` WHERE `user_iduser` = ?);
            DELETE FROM `feed` WHERE `user_iduser` = ?;
            DELETE FROM `userGroup` WHERE `user_iduser` = ?;
            SET FOREIGN_KEY_CHECKS=1;', array($oUser->getId(), $oUser->getId(), $oUser->getId()));
            if ($oStatement === false) {
                die('Unable to delete mapped user records');
            }

            $oUser->delete();
        } else {
            echo 'Error: Unable to retrieve and delete the user generated by the register method unit test';
        }
    }
    
}

class TestException extends \Exception
{
}
