<?php
namespace Library\Core\Orm;

/**
 * Scaffolding class
 *
 * @todo generer entités et collections, les vues controlleur qui implemente directement les methodes du CrudController et les traductions etc...
 */
class EntityScaffold
{

    public function generateEntity($sTableName, $iCacheDuration = 120)
    {
        if (! empty($sTableName)) {
            return '<?php

namespace app\Entities;

/**
 * ' . $sEntityName . ' entity statement
 *
 * @author generated by Core \Libray\Core\Scaffold
 */

class [Computed entity name] extends \Library\Core\Entity {

    const ENTITY = "' . $sEntityName . '";
    const TABLE_NAME = "' . $sTableName . '";
    const PRIMARY_KEY = "id' . strtolower($sEntityName) . '";

    /**
     * Object caching duration in seconds
     * @var integer
     */
    protected $iCacheDuration = ' . $iCacheDuration . ';

    protected $aLinkedEntities = array();

}
            ';
        }

        return false;
    }

}

class CoreScaffoldingException extends \Exception
{
}

